### ISSUE TITLE
twitter integration

### ISSUE THREAD

**Issue by stephanlindauer** [stephanlindauer/criticalmaps-android#13]

**Comment by stephanlindauer** [comment]
done.
@headione should i go for "criticalmaps" without @ or # then?

**Comment by headione** [comment]
yeh i'd go for hash.

**Comment by stephanlindauer** [comment]
i actually went for "criticalmaps" without anything now... :P
should i use hash? do you want to use my backend endpoint for getting tweets from the twitter api?
