### ISSUE TITLE
How to CM at the first start of the app

### ISSUE THREAD

**Issue by ces92** [stephanlindauer/criticalmaps-android#16]
A friend installed the app and was a little bit confused. It would be a good idea show at the first start of the app a how to CM.

**Comment by stephanlindauer** [comment]
really good idea. we already kinda have that in our backlog. thx for the feedback!

**Comment by stephanlindauer** [comment]
i addded a loadiing spinner for when the location is first received. will be in the next release next week. please have a look and let me know if there a further features you want to see implemented.

**Comment by headione** [comment]
maybe we should implement something like intro screens or "take a tour" feature on the next versions.

**Comment by stephanlindauer** [comment]
![screenshot_2015-08-31-02-46-06](https://cloud.githubusercontent.com/assets/1323145/9570396/8c519b98-4f8a-11e5-8950-8930099de482.png)

**Comment by stephanlindauer** [comment]
i added this today. will only be shown the very first time the user opens the app.
