### ISSUE TITLE
remember/recall last position on exit/startup

### ISSUE THREAD

**Issue by rigid** [stephanlindauer/criticalmaps-android#21]
if i leave the map/app, the map always pans back to berlin. The last position should be restored.

**Comment by stephanlindauer** [comment]
this should actually already work. it takes the lastKnownLocation from you device. the last fallback is berlin is berlin and will soon be europe on a higher zoom level. do you have gps enabled on your device? maybe cyanogen blocking?

**Comment by rigid** [comment]
yes, it's probably CM blocking. 
Maybe it's a good idea to only use this for the first run and separatly remember the last position acquired by the app?

**Comment by stephanlindauer** [comment]
by "acuired by the app" you mean the last location and zoom level the user actually moved to? sounds good. i think i'll put this into the next release.

**Comment by rigid** [comment]
:+1:

**Comment by stephanlindauer** [comment]
so what i am working on right now is: when the users opens the app (was closed before) it waits until it gets the first location update until it sets the map location. in the background it either sets the lastKnownLocation oder whatever we have stored in the sharedPrefs. sounds reasonable?

**Comment by stephanlindauer** [comment]
done
