### ISSUE TITLE
turkish translation

### ISSUE THREAD

**Issue by stephanlindauer** [stephanlindauer/criticalmaps-android#22]
hi @canerbasaran ,
can you have another look into the turkish strings file?
a few things have changed and it would be nice to have them in the next release.
tesekkurler abi ;)

**Comment by canerbasaran** [comment]
@stephanlindauer 
https://github.com/canerbasaran/criticalmaps-android/commit/41c8ec6cfa9006d64da48e7af065701ce57fa714
keine ursache!

**Comment by stephanlindauer** [comment]
merged. thx!
