### ISSUE TITLE
Pull support-v4 from local support repository

### ISSUE THREAD

**Issue by krt16s** [stephanlindauer/criticalmaps-android#25]
If you have the SDK installed, you should have a local maven repository serving this file instead of including it as binary jar file. E.g. `compile "com.android.support:support-v4:23.0.0"` in your dependencies in app/build.gradle should work fine.

**Comment by stephanlindauer** [comment]
true. will fix tomorrow. thanks for noticing! ;)

**Comment by stephanlindauer** [comment]
tried to fix it via github.com on my mobile and failed horribly. probably missing a respository. will try again tomorrow. ;)

**Comment by stephanlindauer** [comment]
done
